spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: route1
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: route2
          uri: https://www.jd.com
          predicates:
            - Query=url,jd

server:
  port: 8070
